In [88]:
# Importing Pandas and NumPy
import pandas as pd
import numpy as np

In [89]:
# Importing dataset
df = pd.read_csv('Log_Analysis.csv')

In [90]:
df.head()

,Date,Time,Hours,Min,Seconds,Miliseconds,Process_name,Num_id,Description,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,20171223,22:15:29:606,22,15,29,606,Step_LSC,30002312,onStandStepChanged 3579,NaN,NaN,NaN,NaN
1,20171223,22:15:29:615,22,15,29,615,Step_LSC,30002312,onExtend:1514038530000 14 0 4,NaN,NaN,NaN,NaN
2,20171223,22:15:29:633,22,15,29,633,Step_StandReportReceiver,30002312,onReceive action: android.intent.action.SCREEN_ON,NaN,NaN,NaN,NaN
3,20171223,22:15:29:635,22,15,29,635,Step_LSC,30002312,processHandleBroadcastAction action:android.in...,NaN,NaN,NaN,NaN
4,20171223,22:15:29:635,22,15,29,635,Step_StandStepCounter,30002312,flush sensor data,NaN,NaN,NaN,NaN

In [91]:
#dropping columns
df= df.drop(['Min','Seconds','Miliseconds','Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12'],axis =1)

In [92]:
df

,Date,Time,Hours,Process_name,Num_id,Description
0,20171223,22:15:29:606,22,Step_LSC,30002312,onStandStepChanged 3579
1,20171223,22:15:29:615,22,Step_LSC,30002312,onExtend:1514038530000 14 0 4
2,20171223,22:15:29:633,22,Step_StandReportReceiver,30002312,onReceive action: android.intent.action.SCREEN_ON
3,20171223,22:15:29:635,22,Step_LSC,30002312,processHandleBroadcastAction action:android.in...
4,20171223,22:15:29:635,22,Step_StandStepCounter,30002312,flush sensor data
...,...,...,...,...,...,...
1995,20171224,0:58:53:985,0,Step_LSC,30002312,processHandleBroadcastAction action:android.in...
1996,20171224,0:59:7:581,0,Step_LSC,30002312,processHandleBroadcastAction action:android.in...
1997,20171224,1:0:0:794,1,Step_LSC,30002312,processHandleBroadcastAction action:android.in...
1998,20171224,1:1:0:935,1,Step_LSC,30002312,processHandleBroadcastAction action:android.in...
1999,20171224,1:2:35:789,1,Step_LSC,30002312,processHandleBroadcastAction action:android.in...

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          2000 non-null   int64
 1   Time          2000 non-null   object
 2   Hours         2000 non-null   int64
 3   Process_name  2000 non-null   object
 4   Num_id        2000 non-null   int64
 5   Description   2000 non-null   object
dtypes: int64(3), object(3)
memory usage: 93.9+ KB

In [94]:
missing = df.isnull().sum()
missing

Date            0
Time            0
Hours           0
Process_name    0
Num_id          0
Description     0
dtype: int64

__No Missing Values Found__

### Analyzing the log and investigating if there are any patterns

In [95]:
(df['Date'].value_counts(normalize=True)*100).sort_index()

20171223    88.8
20171224    11.2
Name: Date, dtype: float64

__We can observe there are only two dates data here, i.e 23Dec2017 and 24Dec2017 of which 89% of the data is dated to 23rd Dec__

In [96]:
(df['Hours'].value_counts(normalize=True)*100).sort_index()

0     11.05
1      0.15
22    62.15
23    26.65
Name: Hours, dtype: float64

__Observation__
- We can observe at 22 and 23 hours the maximum process are running, may be because it is end of the day. So this data is dependant on some of those attributes where the processes runs in EOD

In [97]:
(df['Process_name'].value_counts(normalize=True)*100).sort_index()

HiH_                            0.50
HiH_DataStatManager             0.85
HiH_HiAppUtil                   0.40
HiH_HiBroadcastUtil             0.25
HiH_HiHealthBinder              0.45
HiH_HiHealthDataInsertStore     0.55
HiH_HiSyncControl               2.10
HiH_HiSyncUtil                  0.10
HiH_ListenerManager             0.10
Step_DataCache                  0.05
Step_ExtSDM                    24.10
Step_FlushableStepDataCache     0.40
Step_HGNH                       0.10
Step_LSC                       35.50
Step_NotificationUtil           0.05
Step_SPUtils                   24.70
Step_ScreenUtil                 0.05
Step_StandReportReceiver        8.55
Step_StandStepCounter           0.95
Step_StandStepDataManager       0.25
Name: Process_name, dtype: float64

__Here we observed that value count for `Step_LSC`, `Step_SPUtils` and `Step_ExtSDM` is maximum , covering around `85%` of the data. We will try to find pattern over the above three attributes.__

In [98]:
(df['Num_id'].value_counts(normalize=True)*100).sort_index()

30002312    100.0
Name: Num_id, dtype: float64

__Since we have only one type of data in column `Num_id`, we will drop this__

In [99]:
df= df.drop('Num_id',axis=1)

In [100]:
df.loc[(df['Process_name'] == 'Step_LSC')].head(10)

,Date,Time,Hours,Process_name,Description
0,20171223,22:15:29:606,22,Step_LSC,onStandStepChanged 3579
1,20171223,22:15:29:615,22,Step_LSC,onExtend:1514038530000 14 0 4
3,20171223,22:15:29:635,22,Step_LSC,processHandleBroadcastAction action:android.in...
7,20171223,22:15:29:636,22,Step_LSC,onStandStepChanged 3579
11,20171223,22:15:29:737,22,Step_LSC,onExtend:1514038530000 0 0 4
12,20171223,22:15:29:738,22,Step_LSC,onStandStepChanged 3579
13,20171223,22:15:29:792,22,Step_LSC,onStandStepChanged 3580
14,20171223,22:15:29:800,22,Step_LSC,onExtend:1514038530000 1 0 4
20,20171223,22:15:30:331,22,Step_LSC,onStandStepChanged 3581
21,20171223,22:15:30:335,22,Step_LSC,onExtend:1514038531000 1 0 4

In [101]:
df.loc[(df['Process_name'] == 'Step_ExtSDM')].head(10)

,Date,Time,Hours,Process_name,Description
8,20171223,22:15:29:645,22,Step_ExtSDM,calculateCaloriesWithCache totalCalories=126775
9,20171223,22:15:29:648,22,Step_ExtSDM,calculateAltitudeWithCache totalAltitude=240
17,20171223,22:15:29:959,22,Step_ExtSDM,calculateCaloriesWithCache totalCalories=126797
18,20171223,22:15:29:962,22,Step_ExtSDM,calculateAltitudeWithCache totalAltitude=240
24,20171223,22:15:30:639,22,Step_ExtSDM,calculateCaloriesWithCache totalCalories=126818
25,20171223,22:15:30:641,22,Step_ExtSDM,calculateAltitudeWithCache totalAltitude=240
31,20171223,22:15:31:157,22,Step_ExtSDM,calculateCaloriesWithCache totalCalories=126861
32,20171223,22:15:31:160,22,Step_ExtSDM,calculateAltitudeWithCache totalAltitude=240
38,20171223,22:15:32:156,22,Step_ExtSDM,calculateCaloriesWithCache totalCalories=126882
39,20171223,22:15:32:162,22,Step_ExtSDM,calculateAltitudeWithCache totalAltitude=240

__Observation__
- We can find a pattern here and observe that calories calculation and altitude calculation process is repeated back to back after a set interval.
- There is an interval of 6-8 processes before the calories and altitude calculation takes place.

In [102]:
df.loc[(df['Process_name'] == 'Step_SPUtils')].head(20)

,Date,Time,Hours,Process_name,Description
5,20171223,22:15:29:635,22,Step_SPUtils,getTodayTotalDetailSteps = 1514038440000##699...
6,20171223,22:15:29:636,22,Step_SPUtils,setTodayTotalDetailSteps=1514038440000##7007##...
15,20171223,22:15:29:950,22,Step_SPUtils,getTodayTotalDetailSteps = 1514038440000##700...
16,20171223,22:15:29:950,22,Step_SPUtils,setTodayTotalDetailSteps=1514038440000##7008##...
22,20171223,22:15:30:632,22,Step_SPUtils,getTodayTotalDetailSteps = 1514038440000##700...
23,20171223,22:15:30:632,22,Step_SPUtils,setTodayTotalDetailSteps=1514038440000##7009##...
29,20171223,22:15:31:142,22,Step_SPUtils,getTodayTotalDetailSteps = 1514038440000##700...
30,20171223,22:15:31:143,22,Step_SPUtils,setTodayTotalDetailSteps=1514038440000##7011##...
36,20171223,22:15:32:145,22,Step_SPUtils,getTodayTotalDetailSteps = 1514038440000##701...
37,20171223,22:15:32:147,22,Step_SPUtils,setTodayTotalDetailSteps=1514038440000##7012##...
43,20171223,22:15:32:647,22,Step_SPUtils,getTodayTotalDetailSteps = 1514038440000##701...
44,20171223,22:15:32:648,22,Step_SPUtils,setTodayTotalDetailSteps=1514038440000##7013##...
50,20171223,22:15:33:144,22,Step_SPUtils,getTodayTotalDetailSteps = 1514038440000##701...
51,20171223,22:15:33:144,22,Step_SPUtils,setTodayTotalDetailSteps=1514038440000##7014##...
57,20171223,22:15:33:643,22,Step_SPUtils,getTodayTotalDetailSteps = 1514038440000##701...
58,20171223,22:15:33:644,22,Step_SPUtils,setTodayTotalDetailSteps=1514038440000##7015##...
67,20171223,22:15:35:11,22,Step_SPUtils,getTodayTotalDetailSteps = 1514038440000##701...
68,20171223,22:15:35:12,22,Step_SPUtils,setTodayTotalDetailSteps=1514038440000##7017##...
77,20171223,22:15:35:98,22,Step_SPUtils,getTodayTotalDetailSteps = 1514038440000##701...
78,20171223,22:15:35:98,22,Step_SPUtils,setTodayTotalDetailSteps=1514038440000##7017##...

__Observation__
- We can find a pattern here and observe that gettodaydetailssteps and settodaydetailssteps is repeated back to back after a set interval.
- Here also there is an interval of 6-8 processes before the set and get processes takes place.

In [103]:
df

,Date,Time,Hours,Process_name,Description
0,20171223,22:15:29:606,22,Step_LSC,onStandStepChanged 3579
1,20171223,22:15:29:615,22,Step_LSC,onExtend:1514038530000 14 0 4
2,20171223,22:15:29:633,22,Step_StandReportReceiver,onReceive action: android.intent.action.SCREEN_ON
3,20171223,22:15:29:635,22,Step_LSC,processHandleBroadcastAction action:android.in...
4,20171223,22:15:29:635,22,Step_StandStepCounter,flush sensor data
...,...,...,...,...,...
1995,20171224,0:58:53:985,0,Step_LSC,processHandleBroadcastAction action:android.in...
1996,20171224,0:59:7:581,0,Step_LSC,processHandleBroadcastAction action:android.in...
1997,20171224,1:0:0:794,1,Step_LSC,processHandleBroadcastAction action:android.in...
1998,20171224,1:1:0:935,1,Step_LSC,processHandleBroadcastAction action:android.in...
1999,20171224,1:2:35:789,1,Step_LSC,processHandleBroadcastAction action:android.in...

__Correlation Observation__
- We found a very high corelation between Step_SPUtils and Step_ExtSDM.
- Here if `Step_SPUtils` process occurs, it is immediately folllowed by `Step_ExtSDM` !!

### Note:
- The usecase is attached along with the main excel.